all clean:
	$(MAKE) -f Makefile.decode $@
	$(MAKE) -f Makefile.encode $@

distclean: clean
	rm -rf autom4te.cache config.log config.status autom4te.cache
	rm -f Makefile.encode Makefile.decode encode decode
