name: CI

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Build and test module
      uses: savonet/build-and-test-ocaml-module@main
      with:
        extra-packages: ogg
    - name: Run CI tests.
      run: |
        eval $(opam env)
        sudo apt-get install -qq -yy ffmpeg
        dune build @citest
